#include "PropagationMPlex.h"

//#define DEBUG
#include "Debug.h"

#include "KalmanUtilsMPlex.h"

namespace mkfit {

  template void portable::kalmanUpdate<NN>(const MPlexLS<NN>& psErr,
                                           const MPlexLV<NN>& psPar,
                                           const MPlexHS<NN>& msErr,
                                           const MPlexHV<NN>& msPar,
                                           MPlexLS<NN>& outErr,
                                           MPlexLV<NN>& outPar,
                                           const int N_proc);
  template void portable::kalmanPropagateAndUpdate<NN>(const MPlexLS<NN>& psErr,
                                                       const MPlexLV<NN>& psPar,
                                                       MPlexQI<NN>& Chg,
                                                       const MPlexHS<NN>& msErr,
                                                       const MPlexHV<NN>& msPar,
                                                       MPlexLS<NN>& outErr,
                                                       MPlexLV<NN>& outPar,
                                                       MPlexQI<NN>& outFailFlag,
                                                       const int N_proc,
                                                       const PropagationFlags& propFlags,
                                                       const bool propToHit);
  template void portable::kalmanComputeChi2<NN>(const MPlexLS<NN>& psErr,
                                                const MPlexLV<NN>& psPar,
                                                const MPlexQI<NN>& inChg,
                                                const MPlexHS<NN>& msErr,
                                                const MPlexHV<NN>& msPar,
                                                MPlexQF<NN>& outChi2,
                                                const int N_proc);
  template void portable::kalmanPropagateAndComputeChi2<NN>(const MPlexLS<NN>& psErr,
                                                            const MPlexLV<NN>& psPar,
                                                            const MPlexQI<NN>& inChg,
                                                            const MPlexHS<NN>& msErr,
                                                            const MPlexHV<NN>& msPar,
                                                            MPlexQF<NN>& outChi2,
                                                            MPlexLV<NN>& propPar,
                                                            MPlexQI<NN>& outFailFlag,
                                                            const int N_proc,
                                                            const PropagationFlags& propFlags,
                                                            const bool propToHit);
  template void portable::kalmanOperation<NN>(const int kfOp,
                                              const MPlexLS<NN>& psErr,
                                              const MPlexLV<NN>& psPar,
                                              const MPlexHS<NN>& msErr,
                                              const MPlexHV<NN>& msPar,
                                              MPlexLS<NN>& outErr,
                                              MPlexLV<NN>& outPar,
                                              MPlexQF<NN>& outChi2,
                                              const int N_proc);
  template void portable::kalmanUpdateEndcap<NN>(const MPlexLS<NN>& psErr,
                                                 const MPlexLV<NN>& psPar,
                                                 const MPlexHS<NN>& msErr,
                                                 const MPlexHV<NN>& msPar,
                                                 MPlexLS<NN>& outErr,
                                                 MPlexLV<NN>& outPar,
                                                 const int N_proc);
  template void portable::kalmanPropagateAndUpdateEndcap<NN>(const MPlexLS<NN>& psErr,
                                                             const MPlexLV<NN>& psPar,
                                                             MPlexQI<NN>& Chg,
                                                             const MPlexHS<NN>& msErr,
                                                             const MPlexHV<NN>& msPar,
                                                             MPlexLS<NN>& outErr,
                                                             MPlexLV<NN>& outPar,
                                                             MPlexQI<NN>& outFailFlag,
                                                             const int N_proc,
                                                             const PropagationFlags& propFlags,
                                                             const bool propToHit);
  template void portable::kalmanComputeChi2Endcap<NN>(const MPlexLS<NN>& psErr,
                                                      const MPlexLV<NN>& psPar,
                                                      const MPlexQI<NN>& inChg,
                                                      const MPlexHS<NN>& msErr,
                                                      const MPlexHV<NN>& msPar,
                                                      MPlexQF<NN>& outChi2,
                                                      const int N_proc);
  template void portable::kalmanPropagateAndComputeChi2Endcap<NN>(const MPlexLS<NN>& psErr,
                                                                  const MPlexLV<NN>& psPar,
                                                                  const MPlexQI<NN>& inChg,
                                                                  const MPlexHS<NN>& msErr,
                                                                  const MPlexHV<NN>& msPar,
                                                                  MPlexQF<NN>& outChi2,
                                                                  MPlexLV<NN>& propPar,
                                                                  MPlexQI<NN>& outFailFlag,
                                                                  const int N_proc,
                                                                  const PropagationFlags& propFlags,
                                                                  const bool propToHit);
  template void portable::kalmanOperationEndcap<NN>(const int kfOp,
                                                    const MPlexLS<NN>& psErr,
                                                    const MPlexLV<NN>& psPar,
                                                    const MPlexHS<NN>& msErr,
                                                    const MPlexHV<NN>& msPar,
                                                    MPlexLS<NN>& outErr,
                                                    MPlexLV<NN>& outPar,
                                                    MPlexQF<NN>& outChi2,
                                                    const int N_proc);
  template void portable::kalmanUpdatePlane<NN>(const MPlexLS<NN>& psErr,
                                                const MPlexLV<NN>& psPar,
                                                const MPlexQI<NN>& Chg,
                                                const MPlexHS<NN>& msErr,
                                                const MPlexHV<NN>& msPar,
                                                const MPlexHV<NN>& plNrm,
                                                const MPlexHV<NN>& plDir,
                                                const MPlexHV<NN>& plPnt,
                                                MPlexLS<NN>& outErr,
                                                MPlexLV<NN>& outPar,
                                                const int N_proc);
  template void portable::kalmanPropagateAndUpdatePlane<NN>(const MPlexLS<NN>& psErr,
                                                            const MPlexLV<NN>& psPar,
                                                            MPlexQI<NN>& Chg,
                                                            const MPlexHS<NN>& msErr,
                                                            const MPlexHV<NN>& msPar,
                                                            const MPlexHV<NN>& plNrm,
                                                            const MPlexHV<NN>& plDir,
                                                            const MPlexHV<NN>& plPnt,
                                                            MPlexLS<NN>& outErr,
                                                            MPlexLV<NN>& outPar,
                                                            MPlexQI<NN>& outFailFlag,
                                                            const int N_proc,
                                                            const PropagationFlags& propFlags,
                                                            const bool propToHit);
  template void portable::kalmanPropagateAndUpdateAndChi2Plane<NN, cpe_func>(const MPlexLS<NN>& psErr,
                                                                             const MPlexLV<NN>& psPar,
                                                                             MPlexQI<NN>& Chg,
                                                                             const MPlexHS<NN>& msErr,
                                                                             const MPlexHV<NN>& msPar,
                                                                             const MPlexHV<NN>& plNrm,
                                                                             const MPlexHV<NN>& plDir,
                                                                             const MPlexHV<NN>& plPnt,
                                                                             MPlexLS<NN>& outErr,
                                                                             MPlexLV<NN>& outPar,
                                                                             MPlexQI<NN>& outFailFlag,
                                                                             MPlexQF<NN>& outChi2,
                                                                             const int N_proc,
                                                                             const PropagationFlags& propFlags,
                                                                             const bool propToHit,
                                                                             const MPlexQI<NN>* noMatEffPtr,
                                                                             const MPlexQI<NN>* doCPE,
                                                                             cpe_func cpe_corr_func);
  template void portable::kalmanComputeChi2Plane<NN>(const MPlexLS<NN>& psErr,
                                                     const MPlexLV<NN>& psPar,
                                                     const MPlexQI<NN>& inChg,
                                                     const MPlexHS<NN>& msErr,
                                                     const MPlexHV<NN>& msPar,
                                                     const MPlexHV<NN>& plNrm,
                                                     const MPlexHV<NN>& plDir,
                                                     const MPlexHV<NN>& plPnt,
                                                     MPlexQF<NN>& outChi2,
                                                     const int N_proc);
  template void portable::kalmanPropagateAndComputeChi2Plane<NN>(const MPlexLS<NN>& psErr,
                                                                 const MPlexLV<NN>& psPar,
                                                                 const MPlexQI<NN>& inChg,
                                                                 const MPlexHS<NN>& msErr,
                                                                 const MPlexHV<NN>& msPar,
                                                                 const MPlexHV<NN>& plNrm,
                                                                 const MPlexHV<NN>& plDir,
                                                                 const MPlexHV<NN>& plPnt,
                                                                 MPlexQF<NN>& outChi2,
                                                                 MPlexLV<NN>& propPar,
                                                                 MPlexQI<NN>& outFailFlag,
                                                                 const int N_proc,
                                                                 const PropagationFlags& propFlags,
                                                                 const bool propToHit);
  template void portable::kalmanOperationPlane<NN>(const int kfOp,
                                                   const MPlexLS<NN>& psErr,
                                                   const MPlexLV<NN>& psPar,
                                                   const MPlexQI<NN>& Chg,
                                                   const MPlexHS<NN>& msErr,
                                                   const MPlexHV<NN>& msPar,
                                                   const MPlexHV<NN>& plNrm,
                                                   const MPlexHV<NN>& plDir,
                                                   const MPlexHV<NN>& plPnt,
                                                   MPlexLS<NN>& outErr,
                                                   MPlexLV<NN>& outPar,
                                                   MPlexQF<NN>& outChi2,
                                                   const int N_proc);
  template void portable::kalmanOperationPlaneLocal<NN, cpe_func>(const int kfOp,
                                                                  const MPlexLS<NN>& psErr,
                                                                  const MPlexLV<NN>& psPar,
                                                                  const MPlexQI<NN>& Chg,
                                                                  const MPlexHS<NN>& msErr,
                                                                  const MPlexHV<NN>& msPar,
                                                                  const MPlexHV<NN>& plNrm,
                                                                  const MPlexHV<NN>& plDir,
                                                                  const MPlexHV<NN>& plPnt,
                                                                  MPlexLS<NN>& outErr,
                                                                  MPlexLV<NN>& outPar,
                                                                  MPlexQF<NN>& outChi2,
                                                                  const int N_proc,
                                                                  const MPlexQI<NN>* doCPE,
                                                                  cpe_func cpe_corr_func);

}  // end namespace mkfit
