name: Static checks

on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}-${{ contains(github.event.comment.body, '/run checks') || contains(github.event.comment.body, '/run all') }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  linter:
    if: >
      github.event.issue.pull_request &&
      (contains(github.event.comment.body, '/run checks') || contains(github.event.comment.body, '/run all') || contains(github.event.comment.body, '/run gpu-all')) &&
      ( github.event.comment.user.login == 'ariostas' ||
        github.event.comment.user.login == 'GNiendorf' ||
        github.event.comment.user.login == 'YonsiG' ||
        github.event.comment.user.login == 'VourMa' ||
        github.event.comment.user.login == 'aashayarora' ||
        github.event.comment.user.login == 'bucket420' ||
        github.event.comment.user.login == 'jchismar' ||
        github.event.comment.user.login == 'kk428' ||
        github.event.comment.user.login == 'Hoobidoobidoo' ||
        github.event.comment.user.login == 'mmasciov' ||
        github.event.comment.user.login == 'pwittich' ||
        github.event.comment.user.login == 'sgnoohc' ||
        github.event.comment.user.login == 'slava77devel' ||
        github.event.comment.user.login == 'slava77'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
      - name: Get commit SHA
        run: |
          sha=$(git rev-parse HEAD)
          echo "COMMIT_SHA=$sha" >> $GITHUB_ENV
      - name: Create App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          skip-token-revoke: true
      - name: Create in progress check
        uses: LouisBrunner/checks-action@v2.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          sha: ${{ env.COMMIT_SHA }}
          name: Static Checks
          status: in_progress
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          output: |
            {"title": "This check has started...", "summary": "The logs can be found [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."}
      - name: Run static checks with SCRAM
        timeout-minutes: 100
        uses: SegmentLinking/TrackLooper-actions/static-checks@cmssw
        with:
          pr-number: ${{ github.event.issue.number }}
      - name: Create App Token
        if: always()
        uses: actions/create-github-app-token@v1
        id: app-token-end
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create completed check
        uses: LouisBrunner/checks-action@v2.0.0
        if: always()
        with:
          token: ${{ steps.app-token-end.outputs.token }}
          sha: ${{ env.COMMIT_SHA }}
          name: Static Checks
          conclusion: ${{ job.status }}
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          output: |
            {"title": "Status: ${{ job.status }}", "summary": "The logs can be found [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."}
