name: Sync master branch

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Pull master from upsteam and update fork
        run: |
          git remote add upstream https://github.com/cms-sw/cmssw.git
          git fetch upstream
          git pull upstream master
          git push
